POST http://localhost:3001/api/phones HTTP/1.1
Content-Type: application/json


    {   
        "name": "Huawei P30 Pro",
        "manufacturer": "Huawei",
        "description": "lorem ipsum dolor sit amet consectetur",
        "color": "Black",
        "price": 330,
        "imageFileName": "huawei_P30.jpg",
        "screen": "6.1 inch OLED",
        "processor": "Kirin 980",
        "ram": 6
    }
